name: timeit
description: "A new Flutter project for TimeIt."

# The following line prevents the package from being accidentally published to
# pub.dev using flutter pub publish. This is preferred for private packages.
publish_to: 'none'  # Remove this line if you wish to publish to pub.dev

# Version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"  # Specify the correct SDK range.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.8  # Update this to the latest version if needed.

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true  # Ensures Material Icons are available.

  # To add assets to your application, add an assets section like this:
  assets:
    - assets/  # This will include all files in the 'assets' directory.
    - assets/fonts/
    - assets/images/lissahlogo.png  # Corrected image file extension.

  # To add custom fonts, you can specify fonts in the 'flutter' section:
  fonts:
    - family: time
      fonts:
        - asset: assets/fonts/RobotoCondensed-Medium.ttf
          weight: 600
        - asset: assets/fonts/RobotoCondensed-Regular.ttf
